// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woody.Infrastructure.Persistence.Context;

#nullable disable

namespace Woody.Infrastructure.Migrations
{
    [DbContext(typeof(WoodyDbContext))]
    [Migration("20260429120000_AddUserNotifications")]
    partial class AddUserNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woody.Domain.Entities.BillingCheckoutAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_session_id");

                    b.Property<string>("StripeSessionUrl")
                        .HasColumnType("text")
                        .HasColumnName("stripe_session_url");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("integer")
                        .HasColumnName("subject_kind");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_billing_checkout_attempts");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_billing_checkout_attempts_idempotency_key");

                    b.HasIndex("UserId", "SubjectKind", "PlanCode", "CommunityId", "Status")
                        .HasDatabaseName("ix_billing_checkout_attempts_user_id_subject_kind_plan_code_co");

                    b.ToTable("billing_checkout_attempts", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.BillingWebhookReceipt", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.HasKey("EventId")
                        .HasName("pk_billing_webhook_receipts");

                    b.ToTable("billing_webhook_receipts", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("HiddenByPostAuthorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_by_post_author_at");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTime?>("PinnedOnPostAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_on_post_at");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("PostId")
                        .IsUnique()
                        .HasDatabaseName("ix_comments_post_id")
                        .HasFilter("pinned_on_post_at IS NOT NULL");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer")
                        .HasColumnName("member_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rules");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_communities");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_communities_owner_user_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_communities_slug");

                    b.ToTable("communities", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityDailyRollup", b =>
                {
                    b.Property<int>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date")
                        .HasColumnName("day_utc");

                    b.Property<int>("MemberLeaves")
                        .HasColumnType("integer")
                        .HasColumnName("member_leaves");

                    b.Property<int>("PageViews")
                        .HasColumnType("integer")
                        .HasColumnName("page_views");

                    b.HasKey("CommunityId", "DayUtc")
                        .HasName("pk_community_daily_rollups");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_daily_rollups_community_id");

                    b.ToTable("community_daily_rollups", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_community_memberships");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_memberships_community_id");

                    b.HasIndex("UserId", "CommunityId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_memberships_user_id_community_id");

                    b.ToTable("community_memberships", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityPostBoost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_community_post_boosts");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_post_boosts_community_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_community_post_boosts_post_id");

                    b.HasIndex("CommunityId", "EndsAtUtc")
                        .HasDatabaseName("ix_community_post_boosts_community_id_ends_at_utc");

                    b.ToTable("community_post_boosts", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunitySubscription", b =>
                {
                    b.Property<int>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<int>("BillingProvider")
                        .HasColumnType("integer")
                        .HasColumnName("billing_provider");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime?>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<string>("PlanCode")
                        .HasColumnType("text")
                        .HasColumnName("plan_code");

                    b.Property<string>("ProviderCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_subscription_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CommunityId")
                        .HasName("pk_community_subscriptions");

                    b.HasIndex("ProviderSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_community_subscriptions_provider_subscription_id")
                        .HasFilter("provider_subscription_id IS NOT NULL");

                    b.ToTable("community_subscriptions", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_community_tags");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_community_tags_community_id");

                    b.ToTable("community_tags", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.ContentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_content_reports");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_content_reports_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_content_reports_post_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_content_reports_reporter_user_id");

                    b.ToTable("content_reports", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InitiatorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("initiator_user_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserHighId")
                        .HasColumnType("integer")
                        .HasColumnName("user_high_id");

                    b.Property<int>("UserLowId")
                        .HasColumnType("integer")
                        .HasColumnName("user_low_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("InitiatorUserId")
                        .HasDatabaseName("ix_conversations_initiator_user_id");

                    b.HasIndex("UserHighId")
                        .HasDatabaseName("ix_conversations_user_high_id");

                    b.HasIndex("UserLowId", "UserHighId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_user_low_id_user_high_id");

                    b.ToTable("conversations", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversations_ordered_pair", "user_low_id < user_high_id");

                            t.HasCheckConstraint("ck_conversations_pending_has_initiator", "(status <> 1) OR (initiator_user_id IS NOT NULL AND (initiator_user_id = user_low_id OR initiator_user_id = user_high_id))");
                        });
                });

            modelBuilder.Entity("Woody.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("last_read_message_id");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("pk_conversation_participants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversation_participants_user_id");

                    b.ToTable("conversation_participants", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.EmailVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_codes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_codes_user_id");

                    b.HasIndex("Email", "CreatedAt")
                        .HasDatabaseName("ix_email_verification_codes_email_created_at");

                    b.ToTable("email_verification_codes", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("FollowingUserId")
                        .HasColumnType("integer")
                        .HasColumnName("following_user_id");

                    b.Property<int>("FollowedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("followed_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("FollowingUserId", "FollowedUserId")
                        .HasName("pk_follows");

                    b.HasIndex("FollowedUserId")
                        .HasDatabaseName("ix_follows_followed_user_id");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_join_requests");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_join_requests_user_id");

                    b.HasIndex("CommunityId", "UserId", "Status")
                        .HasDatabaseName("ix_join_requests_community_id_user_id_status");

                    b.ToTable("join_requests", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_likes");

                    b.HasIndex("UserId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_likes_user_id_target_type_target_id");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.LoginLockout", b =>
                {
                    b.Property<string>("NormalizedLogin")
                        .HasColumnType("text")
                        .HasColumnName("normalized_login");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTime>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failed_at");

                    b.Property<DateTime>("LastFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failed_at");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.HasKey("NormalizedLogin")
                        .HasName("pk_login_lockouts");

                    b.HasIndex("LockoutEndAt")
                        .HasDatabaseName("ix_login_lockouts_lockout_end_at");

                    b.ToTable("login_lockouts", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_messages_sender_user_id");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_conversation_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.MessageAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_message_attachments");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_attachments_message_id");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer")
                        .HasColumnName("community_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTime?>("PinnedOnProfileAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_on_profile_at");

                    b.Property<int>("PublicationContext")
                        .HasColumnType("integer")
                        .HasColumnName("publication_context");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("ix_posts_community_id");

                    b.HasIndex("PublicationContext", "UserId")
                        .HasDatabaseName("ix_posts_publication_context_user_id");

                    b.HasIndex("UserId", "PinnedOnProfileAt")
                        .HasDatabaseName("ix_posts_user_id_pinned_on_profile_at");

                    b.ToTable("posts", null, t =>
                        {
                            t.HasCheckConstraint("ck_posts_publication_context_community", "(publication_context = 2 AND community_id IS NOT NULL) OR (publication_context = 1 AND community_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Woody.Domain.Entities.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_post_images");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_images_post_id");

                    b.ToTable("post_images", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_post_tags");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_tags_post_id");

                    b.ToTable("post_tags", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_user_notifications");

                    b.HasIndex("RecipientUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_notifications_recipient_user_id_created_at_utc");

                    b.HasIndex("RecipientUserId", "ReadAtUtc")
                        .HasDatabaseName("ix_user_notifications_recipient_user_id_read_at_utc");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.ProfileSignal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<string>("Message")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_user_id");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_profile_signals");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_profile_signals_created_at");

                    b.HasIndex("ReceiverUserId")
                        .HasDatabaseName("ix_profile_signals_receiver_user_id");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_profile_signals_sender_user_id");

                    b.HasIndex("SenderUserId", "CreatedAt")
                        .HasDatabaseName("ix_profile_signals_sender_user_id_created_at");

                    b.HasIndex("ReceiverUserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_profile_signals_receiver_user_id_status_created_at");

                    b.HasIndex("SenderUserId", "ReceiverUserId", "Type", "CreatedAt")
                        .HasDatabaseName("ix_profile_signals_sender_user_id_receiver_user_id_type_create");

                    b.ToTable("profile_signals", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.RefreshTokenSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token_sessions");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_sessions_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_sessions_user_id_expires_at");

                    b.ToTable("refresh_token_sessions", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerPic")
                        .HasColumnType("text")
                        .HasColumnName("banner_pic");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("text")
                        .HasColumnName("profile_pic");

                    b.Property<int>("ProfileSignalsIncomingPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("profile_signals_incoming_preference");

                    b.Property<string>("Pronouns")
                        .HasColumnType("text")
                        .HasColumnName("pronouns");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_interests");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_interests_user_id");

                    b.ToTable("user_interests", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserSocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Handle")
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_social_links");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_social_links_user_id");

                    b.ToTable("user_social_links", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BillingProvider")
                        .HasColumnType("integer")
                        .HasColumnName("billing_provider");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime?>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<string>("PlanCode")
                        .HasColumnType("text")
                        .HasColumnName("plan_code");

                    b.Property<string>("ProviderCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_subscription_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ProviderSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_provider_subscription_id")
                        .HasFilter("provider_subscription_id IS NOT NULL");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Woody.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("Woody.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.HasOne("Woody.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_posts_post_id");

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Community", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "Owner")
                        .WithMany("OwnedCommunities")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_communities_users_owner_user_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityDailyRollup", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithMany("DailyRollups")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_daily_rollups_communities_community_id");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityMembership", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithMany("Memberships")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_memberships_communities_community_id");

                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("CommunityMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_memberships_users_user_id");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityPostBoost", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithMany("PostBoosts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_boosts_communities_community_id");

                    b.HasOne("Woody.Domain.Entities.Post", "Post")
                        .WithMany("CommunityPostBoosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_post_boosts_posts_post_id");

                    b.Navigation("Community");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunitySubscription", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithOne("Subscription")
                        .HasForeignKey("Woody.Domain.Entities.CommunitySubscription", "CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_subscriptions_communities_community_id");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Woody.Domain.Entities.CommunityTag", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithMany("Tags")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_tags_communities_community_id");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Woody.Domain.Entities.ContentReport", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_reports_comments_comment_id");

                    b.HasOne("Woody.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_reports_posts_post_id");

                    b.HasOne("Woody.Domain.Entities.User", "Reporter")
                        .WithMany("ContentReports")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_reports_users_reporter_user_id");

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "Initiator")
                        .WithMany("InitiatedConversations")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_conversations_users_initiator_user_id");

                    b.HasOne("Woody.Domain.Entities.User", "UserHigh")
                        .WithMany("ConversationsAsUserHigh")
                        .HasForeignKey("UserHighId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_user_high_id");

                    b.HasOne("Woody.Domain.Entities.User", "UserLow")
                        .WithMany("ConversationsAsUserLow")
                        .HasForeignKey("UserLowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_user_low_id");

                    b.Navigation("Initiator");

                    b.Navigation("UserHigh");

                    b.Navigation("UserLow");
                });

            modelBuilder.Entity("Woody.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_conversations_conversation_id");

                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("ConversationParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_users_user_id");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.EmailVerificationCode", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_verification_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Follow", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "FollowedUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_followed_user_id");

                    b.HasOne("Woody.Domain.Entities.User", "FollowingUser")
                        .WithMany("Following")
                        .HasForeignKey("FollowingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_following_user_id");

                    b.Navigation("FollowedUser");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("Woody.Domain.Entities.JoinRequest", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithMany("JoinRequests")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_join_requests_communities_community_id");

                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("JoinRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_join_requests_users_user_id");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Like", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Message", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("Woody.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_user_id");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Woody.Domain.Entities.MessageAttachment", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachments_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Post", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_posts_communities_community_id");

                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_users_user_id");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_images_posts_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Woody.Domain.Entities.PostTag", b =>
                {
                    b.HasOne("Woody.Domain.Entities.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tags_posts_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_notifications_users_actor_user_id");

                    b.HasOne("Woody.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_users_recipient_user_id");

                    b.Navigation("ActorUser");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Woody.Domain.Entities.ProfileSignal", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "ReceiverUser")
                        .WithMany("ReceivedProfileSignals")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_signals_users_receiver_user_id");

                    b.HasOne("Woody.Domain.Entities.User", "SenderUser")
                        .WithMany("SentProfileSignals")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_signals_users_sender_user_id");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Woody.Domain.Entities.RefreshTokenSession", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("RefreshTokenSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserInterest", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserSocialLink", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithMany("SocialLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_social_links_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("Woody.Domain.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("Woody.Domain.Entities.UserSubscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Community", b =>
                {
                    b.Navigation("DailyRollups");

                    b.Navigation("JoinRequests");

                    b.Navigation("Memberships");

                    b.Navigation("PostBoosts");

                    b.Navigation("Posts");

                    b.Navigation("Subscription");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Message", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Woody.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CommunityPostBoosts");

                    b.Navigation("Images");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Woody.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CommunityMemberships");

                    b.Navigation("ContentReports");

                    b.Navigation("ConversationParticipations");

                    b.Navigation("ConversationsAsUserHigh");

                    b.Navigation("ConversationsAsUserLow");

                    b.Navigation("EmailVerificationCodes");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("InitiatedConversations");

                    b.Navigation("Interests");

                    b.Navigation("JoinRequests");

                    b.Navigation("Likes");

                    b.Navigation("OwnedCommunities");

                    b.Navigation("Posts");

                    b.Navigation("ReceivedProfileSignals");

                    b.Navigation("RefreshTokenSessions");

                    b.Navigation("SentMessages");

                    b.Navigation("SentProfileSignals");

                    b.Navigation("SocialLinks");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
